
networks:
  application:
    external:
      name: db_application

services:
  spring-boot-app:
    build:
      context: ""
      dockerfile: backend/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/e-commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8082:8080
    networks:
      - application
